### ISSUE TITLE
Accessory not removed from HomeKit when removed from config

### ISSUE THREAD

**Issue by kurtwarwick-new** [kurtwarwick-new/homebridge-appletv-now-playing#22]
The accessories loaded into HomeKit are not removed if they are taken out of the config section.

**Comment by kurtwarwick-new** [comment]
Fixed with latest pull request.

**Comment by maxphour** [comment]
Just to let you now: The apps included in the inputs section are still not removed if they are taken out off the config.

**Comment by kurtwarwick-new** [comment]
Thanks @maxphour 

I have created a new issue for this 😄 

Regards

Kurt
